version: '3.9'

services:
  chatdev:
    build: .
    container_name: chatdev
    tty: true
    env_file:
      - .env
    volumes:
      - type: bind
        source: .
        target: /app
      - type: volume
        source: packages
        target: /usr/local/lib/python3.12/site-packages

volumes:
  packages: